"""Immutable domain models for Proyecto Micelio."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from pydantic import BaseModel, ConfigDict, Field


class DepartmentEnum(str, Enum):
    """Company departments."""
    ENGINEERING = "ENGINEERING"
    PRODUCT = "PRODUCT"
    DATA = "DATA"
    QA = "QA"
    DESIGN = "DESIGN"
    OPERATIONS = "OPERATIONS"


class ProjectStatus(str, Enum):
    """Lifecycle status of a Living Project."""
    DRAFT = "DRAFT"
    DISPATCHED = "DISPATCHED"
    ACTIVE_OFFICE = "ACTIVE_OFFICE"
    COMPLETED = "COMPLETED"


class MembershipStatus(str, Enum):
    """Status of a member's invitation/participation."""
    INVITED = "INVITED"
    JOINED = "JOINED"
    DECLINED = "DECLINED"
    DELIVERED = "DELIVERED"


class SynapseEventType(str, Enum):
    """Types of events transmitted in the Virtual Agent Office."""
    STATE_MUTATION = "STATE_MUTATION"
    AGENT_QUERY = "AGENT_QUERY"
    AGENT_RESPONSE = "AGENT_RESPONSE"
    AGENT_CONSENSUS = "AGENT_CONSENSUS"
    OFFICE_CHATTER = "OFFICE_CHATTER"


class Member(BaseModel):
    """Company collaborator (human)."""
    model_config = ConfigDict(frozen=True)

    id: str
    name: str
    email: str
    department: DepartmentEnum
    is_manager: bool = False


class AgentProfile(BaseModel):
    """AI agent profile associated with a collaborator."""
    model_config = ConfigDict(frozen=True)

    agent_id: str
    member_id: str
    capabilities: tuple[str, ...] = Field(default_factory=tuple)
    workload_pct: float = Field(ge=0.0, le=100.0, default=0.0)


class LivingProject(BaseModel):
    """Central project entity hosted in the living substrate."""
    model_config = ConfigDict(frozen=True)

    id: str
    title: str
    vision: str
    creator_id: str
    status: ProjectStatus = ProjectStatus.DRAFT
    shared_contracts: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class NutrientPackage(BaseModel):
    """Distilled, fluff-free semantic specification sent across hyphae."""
    model_config = ConfigDict(frozen=True)

    project_id: str
    distilled_specs: str
    interfaces: dict[str, Any] = Field(default_factory=dict)
    constraints: tuple[str, ...] = Field(default_factory=tuple)


class TriadBriefing(BaseModel):
    """The mandatory three-axis briefing generated by the worker's agent."""
    model_config = ConfigDict(frozen=True)

    what_arrived: str
    what_was_done: str
    what_to_do: str
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ProjectMembership(BaseModel):
    """Hyphal assignment connecting a collaborator and their agent to a project."""
    model_config = ConfigDict(frozen=True)

    id: str
    project_id: str
    member_id: str
    role_in_project: str
    status: MembershipStatus = MembershipStatus.INVITED
    local_workspace_path: str = ""
    invited_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    joined_at: datetime | None = None


class SynapseEvent(BaseModel):
    """Real-time event flowing through the inter-agent Synapse bus."""
    model_config = ConfigDict(frozen=True)

    event_id: str
    project_id: str
    source_agent_id: str
    target_agent_id: str = "BROADCAST"
    event_type: SynapseEventType
    payload: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
